# Generated by Django 3.0.7 on 2020-07-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20200704_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='user',
        ),
    ]
