# Generated by Django 3.0.7 on 2020-07-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
    ]
