# Generated by Django 3.0.7 on 2020-06-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='time',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
