# Generated by Django 3.0.7 on 2020-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200702_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.CharField(default='---', max_length=120),
        ),
    ]
