# Generated by Django 3.0.7 on 2020-07-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200702_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cat',
            field=models.CharField(choices=[('Category1', 'Category1'), ('Category2', 'Category2')], default='--', max_length=120),
        ),
    ]
